## Preface

In [1]:
# 定義要寫入檔案的內容
content = "ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoštovani, prosim, da zasedete svoja mesta. V naši sredini pozdravljam predsednika države, gospoda Boruta Pahorja in predsednika Državnega zbora, gospoda Janka Vebra. Lepo pozdravljena. [[aplavz]] [[himna]] Besedo dajem spoštovanemu predsedniku Državnega zbora, gospodu Janku Vebru. Izvolite, prosim.\nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2\tHvala za besedo, predsedujoča. Spoštovani predsednik Republike Slovenije, gospod Borut Pahor, spoštovani poslanke in poslanci, gospe in gospodje! Dovolite mi, da vas nagovorim ob izteku VI. mandata Državnega zbora. Mandat se izteka prej, kot določa Ustava, kar govori o tem, da smo delovali v zelo zahtevnih razmerah, ki so jih v veliki meri narekovale tako gospodarske in finančne razmere, ki pa so nastale v svetu, ne v Sloveniji, to moramo poudariti, seveda pa smo sestavni del tega dogajanja bili tudi v Sloveniji. In ukrepi, ki jih je bilo treba sprejemati v Državnem zboru, so bili zelo pomembni, da smo lahko obvladovali ravno to področje. Dosegli smo soglasje tako med opozicijo in koalicijo, zato da smo lahko spremenili v dveh bistvenih točkah tudi Ustavo Republike Slovenije in tudi na mednarodnem področju sprejeli pomembno odločitev, ko smo soglasno ratificirali vstop Republike Hrvaške v Evropsko unijo. \nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u3\tZahvaljujem se spoštovanemu gospodu Janku Vebru, predsedniku Državnega zbora, za izrečene besede. Hvala lepa. Začenjam 1. sejo Državnega zbora, ki jo je na podlagi 81. člena Ustave Republike Slovenije sklical predsednik Republike Slovenije, gospod Borut Pahor, ki bo Državni zbor zdaj tudi nagovoril. Prosim, spoštovani predsednik.\nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u4\tSpoštovana gospa predsedujoča, spoštovane poslanke, spoštovani poslanci! Sprejmite najprej, prosim, moje iskrene čestitke za vašo izvolitev. Po običaju bi zdaj moral najbrž dodati željo, da se skupaj potrudimo po svojih najboljših močeh. Ampak, že dolgo časa ni več ta čas običajen, zato mi pride na misel Churchill. Trud po naših najboljših močeh ni več dovolj. Čas je, da naredimo pravo stvar. \nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u5\tPredsedniku republike, spoštovanemu gospodu Borutu Pahorju, se zahvaljujem za njegove besede in hvala gospod predsednik, da ste počastili Državni zbor s svojo prisotnostjo. Hvala lepa. Obveščena sem, da se današnje seje ne more udeležiti poslanec gospod Luka Mesec. Na sejo Državnega zbora sta vabljena predsednik Državne volilne komisije Anton Gašper Frantar in direktor Službe državne volilne komisije Dušan Vučko, in sicer k 2. točki dnevnega reda. Vse prisotne še enkrat lepo pozdravljam! Pri vodenju seje Državnega zbora mi bosta pomagali generalna sekretarka državnega zbora, gospa Mojca Prelesnik, in namestnica generalne sekretarke, gospa Jerneja Bergoč. Prehajamo na določitev dnevnega reda prve seje Državnega zbora.\nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u33\tZahvaljujem se spoštovanemu dr. Miru Cerarju za podano obrazložitev predloga kandidata za predsednika Državnega zbora. Besedo dajem predstavnikom poslanskih skupin za predstavitev stališč. Besedo ima Poslanska skupina DeSUS, gospod Karl Viktor Erjavec.\nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u34\tHvala lepa. Najprej bi se zahvalil predsedujoči gospe Marjani Kotnik Poropat za odlično vodenje te seje. Čestitam. Čestitam seveda tudi vsem poslankam in poslancem na izvolitev in na potrditev mandata. V stranki DeSUS bomo kandidaturo dr. Milana Brgleza za predsednika Državnega zbora podprli. Podprli jo bomo zato, ker je nujno, da se Državni zbor čim prej konstituira in da čim prej pridemo tudi do vlade. Vemo, kakšna je situacija v državi, in ključno za reševanje problemov, s katerimi se sooča Slovenija, je stabilna politična situacija. \nParlaMint-SI_2014-08-01-SDZ7-Redna-01.u39\tHvala lepa. Besedo ima Poslanska skupina Nova Slovenija – krščanski demokrati. Spoštovana gospa Ljudmila Novak, izvolite.\n"

# 指定檔案名
filename = 'sample.txt'

# 開啟檔案並寫入內容
with open(filename, 'w') as file:
    file.write(content)

print(f'{filename} 已經創建並寫入內容。')

sample.txt 已經創建並寫入內容。

### https://medium.com/@taja.kuzman/from-mr-carrot-to-mr-tr%C4%8Dek-correcting-proper-names-in-machine-translation-49987351c524

In [2]:
!pip install --user -U -q nltk

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 13.9 MB/s eta 0:00:00
  WARNING: The script nltk is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [3]:
file = open("sample.txt", "r").read()

import nltk
nltk.download('punkt')

from nltk.tokenize import sent_tokenize, word_tokenize
sentence_list = sent_tokenize(file)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [4]:
len(sentence_list)

42

In [5]:
sentence_list[:3]

['ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoštovani, prosim, da zasedete svoja mesta.',
 'V naši sredini pozdravljam predsednika države, gospoda Boruta Pahorja in predsednika Državnega zbora, gospoda Janka Vebra.',
 'Lepo pozdravljena.']

In [6]:
from transformers import pipeline

model_OPUS = "Helsinki-NLP/opus-mt-mul-en"
translator_multi = pipeline("translation", model = model_OPUS)

translationMulti = translator_multi(sentence_list)
print(translationMulti[:3])

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/310M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/707k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/791k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.42M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

[{'translation_text': 'ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Please sit down.'}, {'translation_text': 'I welcome the President of the State, Mr Borut Pahor and the President of the State Council, Mr Janka Webra.'}, {'translation_text': 'Nice to meet you.'}]

In [7]:
!pip install -q googletrans==4.0.0-rc1

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 36.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 3.4 MB/s eta 0:00:00
  Building wheel for googletrans (setup.py) ... done

In [8]:
import googletrans

from googletrans import Translator

#Define the model
translator = Translator()

# Translate the entire list and create a list of translations

translation_GT = []

for i in sentence_list:
        current_translation = translator.translate(i, src = "sl", dest='en')
        translation_GT.append(current_translation.text)

print(translation_GT[:3])

['Parlamint-SI_2014-08-01-SDZ7-01.u1 Dear Sirs, please occupy your places.', 'In our midst, I welcome the President of the State, Mr. Borut Pahor and the Speaker of the National Assembly, Mr. Janko Vebra.', 'Hello.']

In [9]:
!pip install -q -U easynmt

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for easynmt (setup.py) ... done
  Building wheel for fasttext (pyproject.toml) ... done

In [10]:
from easynmt import EasyNMT
bart_en = EasyNMT('mbart50_m2en')

translation_bart_en = bart_en.translate(sentence_list, source_lang = 'sl', target_lang='en')
translation_bart_en[:4]

1.47kB [00:00, 2.42MB/s]

config.json:   0%|          | 0.00/1.51k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/268 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/649 [00:00<?, ?B/s]

['ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Ladies and gentlemen, please take your seats.',
 'In our midst, I greet the President of the State, Mr. Borut Pahor, and the President of the National Assembly, Mr. Jank Vebra.',
 'Nice to meet you.',
 '(Applause) (Music) (Applause) I give this bead to the esteemed President of the National Assembly, Mr. Jank Vebra.']

In [11]:
# Create a dataframe with all the results
import pandas as pd

# Add all the lists with original sentences and translations to a DataFrame
# results_df = pd.DataFrame({"source": sentence_list, "OPUS-MT": [x["translation_text"] for x in translationMulti], "Google Translate": translation_GT, "mBART50_m2en": translation_bart_en})
results_df = pd.DataFrame({"text": sentence_list, "translation": [x["translation_text"] for x in translationMulti]})

In [12]:
display(results_df.head(5))

,text,translation
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut..."
2,Lepo pozdravljena.,Nice to meet you.
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...
4,"Izvolite, prosim.","Here you go, please."

In [13]:
results_df.to_csv("sample_txt.csv", index=False)

----

## classla

In [14]:
!pip  install -qU classla

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.9/249.9 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 20.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 kB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 929.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 7.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albucore 0.0.14 requires numpy>=1.24, but you have numpy 1.23.0 which is incompatible.
albumentations 1.4.14 requires numpy>=1.24.4, but you have numpy 1.23.0 which is incompatible.
chex 0.1.86 requires numpy>=1.24.1, but you have numpy 1.23.0 which is incompatible.
dopamine-rl 4.0.9 requires tqdm>=4.64.1, but you have tqdm 4.62.3 which is incompatible.
google-ai-generativelanguage 0.6.6 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-api-core 2.19.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-aiplatform 1.64.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-bigquery-connection 1.15.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-bigquery-storage 2.25.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-bigtable 2.26.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-datastore 2.19.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-firestore 2.16.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-functions 1.16.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-iam 2.15.2 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-language 2.13.4 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-pubsub 2.23.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-resource-manager 1.12.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-translate 3.15.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-colab 1.0.0 requires requests==2.32.3, but you have requests 2.28.0 which is incompatible.
googleapis-common-protos 1.65.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
grpc-google-iam-v1 0.13.1 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
pandas-stubs 2.1.4.231227 requires numpy>=1.26.0; python_version < "3.13", but you have numpy 1.23.0 which is incompatible.
tensorflow 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 1.23.0 which is incompatible.
tensorflow 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 4.21.2 which is incompatible.
tensorflow-metadata 1.15.0 requires protobuf<4.21,>=3.20.3; python_version < "3.11", but you have protobuf 4.21.2 which is incompatible.
torchaudio 2.4.0+cu121 requires torch==2.4.0, but you have torch 1.12.0 which is incompatible.
torchvision 0.19.0+cu121 requires torch==2.4.0, but you have torch 1.12.0 which is incompatible.
yfinance 0.2.43 requires requests>=2.31, but you have requests 2.28.0 which is incompatible.

In [15]:
# Install and download the CLASSLA tool
import classla
classla.download('sl')
nlp = classla.Pipeline('sl', processors='tokenize,ner,pos,lemma')

Downloading https://raw.githubusercontent.com/clarinsi/classla-resources/main/resources_2.1.json: 11.4kB [00:00, 8.21MB/s]
INFO:classla:Downloading these customized packages for language: sl (Slovenian)...
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| depparse  | standard |
| ner       | standard |
| pretrain  | standard |
========================

Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1767/suk_pos: 100%|██████████| 425M/425M [00:16<00:00, 25.4MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1768/suk_lemmatizer.pt: 100%|██████████| 2.19M/2.19M [00:00<00:00, 3.26MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1769/suk_udsyn: 100%|██████████| 90.6M/90.6M [00:05<00:00, 16.4MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1321/ssj500k: 100%|██████████| 48.3M/48.3M [00:02<00:00, 19.6MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1769/sl_ssj.pretrain.pt: 100%|██████████| 110M/110M [00:04<00:00, 24.7MB/s]
INFO:classla:Finished downloading models and saved to /root/classla_resources.
INFO:classla:Loading these models for language: sl (Slovenian):
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| ner       | standard |
========================

INFO:classla:Use device: cpu
INFO:classla:Loading: tokenize
INFO:classla:Loading: pos
/usr/local/lib/python3.10/dist-packages/classla/models/pos/trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
/usr/local/lib/python3.10/dist-packages/classla/models/common/pretrain.py:47: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
INFO:classla:Loading: lemma
/usr/local/lib/python3.10/dist-packages/classla/models/lemma/trainer.py:225: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
/usr/local/lib/python3.10/dist-packages/classla/models/pos/trainer.py:156: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:classla:Loading: ner
/usr/local/lib/python3.10/dist-packages/classla/models/ner/trainer.py:125: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:classla:Done loading processors!

In [16]:
doc = nlp("Hvala. Prehajam na novo točko.").to_dict()

for sentence in doc:
    print(sentence)

([{'id': 1, 'text': 'Hvala', 'lemma': 'hvala', 'upos': 'NOUN', 'xpos': 'Ncfsn', 'feats': 'Case=Nom|Gender=Fem|Number=Sing', 'misc': 'SpaceAfter=No', 'ner': 'O'}, {'id': 2, 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'Z', 'ner': 'O'}], '# newpar id = 1\n# sent_id = 1.1\n# text = Hvala.\n')
([{'id': 1, 'text': 'Prehajam', 'lemma': 'prehajati', 'upos': 'VERB', 'xpos': 'Vmpr1s', 'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'ner': 'O'}, {'id': 2, 'text': 'na', 'lemma': 'na', 'upos': 'ADP', 'xpos': 'Sa', 'feats': 'Case=Acc', 'ner': 'O'}, {'id': 3, 'text': 'novo', 'lemma': 'nov', 'upos': 'ADJ', 'xpos': 'Agpfsa', 'feats': 'Case=Acc|Degree=Pos|Gender=Fem|Number=Sing', 'ner': 'O'}, {'id': 4, 'text': 'točko', 'lemma': 'točka', 'upos': 'NOUN', 'xpos': 'Ncfsa', 'feats': 'Case=Acc|Gender=Fem|Number=Sing', 'misc': 'SpaceAfter=No', 'ner': 'O'}, {'id': 5, 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'Z', 'ner': 'O'}], '# sent_id = 1.2\n# text = Prehajam na novo točko.\n')

In [17]:
results_df.keys()

Index(['text', 'translation'], dtype='object')

In [18]:
results_df.head()

,text,translation
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut..."
2,Lepo pozdravljena.,Nice to meet you.
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...
4,"Izvolite, prosim.","Here you go, please."

## Session 2

In [19]:
source_sentences = results_df['text'].to_list()
len(source_sentences)

42

In [20]:
target_sentences = results_df['translation'].to_list()
tokenized_sentences = []
proper_noun_list = []

In [21]:
#for word in doc[0][0]:
for i in source_sentences:
  doc = nlp(i).to_dict()

  current_sentence_list = []
  word_dict = {}

  for sentence in doc:
    for word in sentence[0]:
      current_sentence_list.append(word["text"])
      current_index = int(word["id"]) - 1

      # Add information on the lemma if the NE is personal name
      if "PER" in word["ner"]:
        word_dict[current_index] = [word["text"], word["lemma"]]


    current_string = " ".join(current_sentence_list)

    tokenized_sentences.append(current_string)

    # Add the proper noun information for the current sentence to list for all sentences
    proper_noun_list.append(word_dict)

# Add the result to the df
results_df["text_tokenized"] = tokenized_sentences
results_df["proper_noun"] = proper_noun_list

In [22]:
results_df.head(5)

,text,translation,text_tokenized,proper_noun
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{}
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...",V naši sredini pozdravljam predsednika države ...,"{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor..."
2,Lepo pozdravljena.,Nice to meet you.,Lepo pozdravljena .,{}
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoš...,"{18: ['Janku', 'Janko'], 19: ['Vebru', 'Veber']}"
4,"Izvolite, prosim.","Here you go, please.","Izvolite , prosim .",{}

If your language is not covered by CLASSLA, you can use Stanza - I will demonstrate how it works on the English translation.

## Stanza

In [23]:
!pip install -q stanza
import stanza

nlp = stanza.Pipeline(lang='en', processors='tokenize,mwt,pos,lemma, ner')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 990.1/990.1 kB 25.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.4/431.4 kB 18.3 MB/s eta 0:00:00

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.8.0.json:   0%|   …

INFO:stanza:Downloaded file to /root/stanza_resources/resources.json

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/tokenize/combined.pt:   0%|    …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/mwt/combined.pt:   0%|         …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/pos/combined_charlm.pt:   0%|  …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/lemma/combined_nocharlm.pt:   0…

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/ner/ontonotes-ww-multi_charlm.p…

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/backward_charlm/1billion.pt:   …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/pretrain/conll17.pt:   0%|     …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/forward_charlm/1billion.pt:   0…

INFO:stanza:Loading these models for language: en (English):
=========================================
| Processor | Package                   |
-----------------------------------------
| tokenize  | combined                  |
| mwt       | combined                  |
| pos       | combined_charlm           |
| lemma     | combined_nocharlm         |
| ner       | ontonotes-ww-multi_charlm |
=========================================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
/usr/local/lib/python3.10/dist-packages/stanza/models/tokenization/trainer.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: mwt
/usr/local/lib/python3.10/dist-packages/stanza/models/mwt/trainer.py:170: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: pos
/usr/local/lib/python3.10/dist-packages/stanza/models/pos/trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
/usr/local/lib/python3.10/dist-packages/stanza/models/common/pretrain.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
/usr/local/lib/python3.10/dist-packages/stanza/models/common/char_model.py:271: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: lemma
/usr/local/lib/python3.10/dist-packages/stanza/models/lemma/trainer.py:236: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: ner
/usr/local/lib/python3.10/dist-packages/stanza/models/ner/trainer.py:197: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Done loading processors!

In [24]:
#Create a list of tokenized text where all words are separated by spaces - this is needed for word alignment
tokenized_sentences = []

# Create a NER and lemma information into which you will save element for each sentence
proper_noun_list = []

# Run the processing on each sentence
for i in target_sentences:
  doc = nlp(i).to_dict()

  # Create a list of words in the current sentence
  current_sentence_list = []

  # Create a dictionary of all information on proper names for the current sentence
  word_dict = {}


  # Loop through the words in the sentence and add them to a current sentence list
  for sentence in doc:
    for word in sentence:
      current_sentence_list.append(word["text"])

      # Find the current index - you need to substract 1 from the word index,
      # because indexing in the process starts with 1, not 0
      if isinstance(word["id"], tuple) and len(word["id"])>1:
        current_index = int(word["id"][0]) - 1
      else:
        current_index = int(word["id"]) - 1

      # Add information on the lemma if the NE is personal name
      if "ner" in word.keys() and "lemma" in word.keys() and "PER" in word["ner"]:
        word_dict[current_index] = [word["text"], word["lemma"]]

  # Join the list into a space-separated string to get tokenized text
  current_string = " ".join(current_sentence_list)

  tokenized_sentences.append(current_string)

  # Add the proper noun information for the current sentence to list for all sentences
  proper_noun_list.append(word_dict)

# Add the result to the df
results_df["En_text_tokenized"] = tokenized_sentences
results_df["En_proper_noun"] = proper_noun_list

In [25]:
results_df.head()

,text,translation,text_tokenized,proper_noun,En_text_tokenized,En_proper_noun
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{}
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...",V naši sredini pozdravljam predsednika države ...,"{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor...","I welcome the President of the State , Mr Boru...","{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']..."
2,Lepo pozdravljena.,Nice to meet you.,Lepo pozdravljena .,{},Nice to meet you .,{}
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoš...,"{18: ['Janku', 'Janko'], 19: ['Vebru', 'Veber']}",I give the floor to the respected President of...,"{14: ['Janku', 'Janku'], 15: ['Vebru', 'Vebru']}"
4,"Izvolite, prosim.","Here you go, please.","Izvolite , prosim .",{},"Here you go , please .",{}

In [26]:
# Create a list of translation sentences
target_sentences = results_df['translation'].to_list()

# Create a list of tokenized text where all words are separated by spaces
# This is needed for word alignment
target_tokenized_sentences = []

# Run the language processing on each sentence
for i in target_sentences:
    # Transform the output into a dictionary
    doc = nlp(i).to_dict()

    # Create a list of words in the current sentence
    current_sentence_list = []

    # Loop through the words in the sentence
    # and add them to a current sentence list
    # to get tokenized sentences
    for sentence in doc:
        for word in sentence:
            # Add the word to the list of words for this sentence
            current_sentence_list.append(word["text"])

    # Join the list into a space-separated string to get tokenized text
    current_string = " ".join(current_sentence_list)

    # Add the tokenized sentence to a list of all sentences
    target_tokenized_sentences.append(current_string)

# Add the result to the df
results_df["translation_tokenized"] = target_tokenized_sentences

In [27]:
results_df.head()

,text,translation,text_tokenized,proper_noun,En_text_tokenized,En_proper_noun,translation_tokenized
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...",V naši sredini pozdravljam predsednika države ...,"{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor...","I welcome the President of the State , Mr Boru...","{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']...","I welcome the President of the State , Mr Boru..."
2,Lepo pozdravljena.,Nice to meet you.,Lepo pozdravljena .,{},Nice to meet you .,{},Nice to meet you .
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoš...,"{18: ['Janku', 'Janko'], 19: ['Vebru', 'Veber']}",I give the floor to the respected President of...,"{14: ['Janku', 'Janku'], 15: ['Vebru', 'Vebru']}",I give the floor to the respected President of...
4,"Izvolite, prosim.","Here you go, please.","Izvolite , prosim .",{},"Here you go , please .",{},"Here you go , please ."

## stanza

In [28]:
!pip install -q stanza

In [29]:
import stanza

nlp = stanza.Pipeline(lang='en', processors='tokenize,mwt,pos,lemma, ner')

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.8.0.json:   0%|   …

INFO:stanza:Downloaded file to /root/stanza_resources/resources.json
INFO:stanza:Loading these models for language: en (English):
=========================================
| Processor | Package                   |
-----------------------------------------
| tokenize  | combined                  |
| mwt       | combined                  |
| pos       | combined_charlm           |
| lemma     | combined_nocharlm         |
| ner       | ontonotes-ww-multi_charlm |
=========================================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
/usr/local/lib/python3.10/dist-packages/stanza/models/tokenization/trainer.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: mwt
/usr/local/lib/python3.10/dist-packages/stanza/models/mwt/trainer.py:170: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: pos
/usr/local/lib/python3.10/dist-packages/stanza/models/pos/trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
/usr/local/lib/python3.10/dist-packages/stanza/models/common/pretrain.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
/usr/local/lib/python3.10/dist-packages/stanza/models/common/char_model.py:271: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: lemma
/usr/local/lib/python3.10/dist-packages/stanza/models/lemma/trainer.py:236: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Loading: ner
/usr/local/lib/python3.10/dist-packages/stanza/models/ner/trainer.py:197: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
INFO:stanza:Done loading processors!

In [30]:

df_copy = results_df.copy(deep=True)
df_copy = df_copy.drop(columns=['text_tokenized', 'proper_noun'])
df_copy.head(10)

,text,translation,En_text_tokenized,En_proper_noun,translation_tokenized
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...","I welcome the President of the State , Mr Boru...","{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']...","I welcome the President of the State , Mr Boru..."
2,Lepo pozdravljena.,Nice to meet you.,Nice to meet you .,{},Nice to meet you .
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,I give the floor to the respected President of...,"{14: ['Janku', 'Janku'], 15: ['Vebru', 'Vebru']}",I give the floor to the respected President of...
4,"Izvolite, prosim.","Here you go, please.","Here you go , please .",{},"Here you go , please ."
5,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2\tHval...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...
6,"Spoštovani predsednik Republike Slovenije, gos...",Respected President of the Republic of Sloveni...,Respected President of the Republic of Sloveni...,"{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']}",Respected President of the Republic of Sloveni...
7,"Dovolite mi, da vas nagovorim ob izteku VI.",Let me talk to you at the VI race.,Let me talk to you at the VI race .,{},Let me talk to you at the VI race .
8,mandata Državnega zbora.,The mandate of the State Council.,The mandate of the State Council .,{},The mandate of the State Council .
9,"Mandat se izteka prej, kot določa Ustava, kar ...","The mandate is preceded by, as laid down in th...","The mandate is preceded by , as laid down in t...",{},"The mandate is preceded by , as laid down in t..."

In [31]:
df_copy.head(10)

,text,translation,En_text_tokenized,En_proper_noun,translation_tokenized
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...","I welcome the President of the State , Mr Boru...","{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']...","I welcome the President of the State , Mr Boru..."
2,Lepo pozdravljena.,Nice to meet you.,Nice to meet you .,{},Nice to meet you .
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,I give the floor to the respected President of...,"{14: ['Janku', 'Janku'], 15: ['Vebru', 'Vebru']}",I give the floor to the respected President of...
4,"Izvolite, prosim.","Here you go, please.","Here you go , please .",{},"Here you go , please ."
5,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2\tHval...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...
6,"Spoštovani predsednik Republike Slovenije, gos...",Respected President of the Republic of Sloveni...,Respected President of the Republic of Sloveni...,"{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']}",Respected President of the Republic of Sloveni...
7,"Dovolite mi, da vas nagovorim ob izteku VI.",Let me talk to you at the VI race.,Let me talk to you at the VI race .,{},Let me talk to you at the VI race .
8,mandata Državnega zbora.,The mandate of the State Council.,The mandate of the State Council .,{},The mandate of the State Council .
9,"Mandat se izteka prej, kot določa Ustava, kar ...","The mandate is preceded by, as laid down in th...","The mandate is preceded by , as laid down in t...",{},"The mandate is preceded by , as laid down in t..."

In [32]:
target_sentences = df_copy['OPUS-MT'].to_list()
target_tokenized_sentences = []


for i in target_sentences:
    doc = nlp(i).to_dict()

    current_sentence_list = []
    word_dict = {}

    for sentence in doc:
        for word in sentence:
            current_sentence_list.append(word["text"])

    # Join the list into a space-separated string to get tokenized text
    current_string = " ".join(current_sentence_list)

    # Add the tokenized sentence to a list of all sentences
    target_tokenized_sentences.append(current_string)

# Add the result to the df
df_copy["translation_tokenized"] = target_tokenized_sentences

KeyError: 'OPUS-MT'

In [ ]:
df_copy

## 2. Align words in the source and translated sentence with Eflomal

In [ ]:
!git clone https://github.com/robertostling/eflomal
%cd eflomal
!make
!sudo make install
!python3 setup.py install

In [ ]:
Slovene_sentences = open("Slovene_sentences.txt", "w")
English_sentences = open("English_sentences.txt", "w")

for i in results_df.text_tokenized.to_list():
	Slovene_sentences.write(i)
	Slovene_sentences.write("\n")

for i in results_df['translation_tokenized'].to_list():
	English_sentences.write(i)
	English_sentences.write("\n")

Slovene_sentences.close()
English_sentences.close()

In [ ]:
!python3 align.py -s "Slovene_sentences.txt" -t "English_sentences.txt" --model 3 -f sl-en.fwd -r sl-en.rev

In [34]:
results_df['text_tokenized'].to_list()

['ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u1 Spoštovani , prosim , da zasedete svoja mesta .',
 'V naši sredini pozdravljam predsednika države , gospoda Boruta Pahorja in predsednika Državnega zbora , gospoda Janka Vebra .',
 'Lepo pozdravljena .',
 '[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoštovanemu predsedniku Državnega zbora , gospodu Janku Vebru .',
 'Izvolite , prosim .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u2 Hvala za besedo , predsedujoča .',
 'Spoštovani predsednik Republike Slovenije , gospod Borut Pahor , spoštovani poslanke in poslanci , gospe in gospodje !',
 'Dovolite mi , da vas nagovorim ob izteku VI .',
 'mandata Državnega zbora .',
 'Mandat se izteka prej , kot določa Ustava , kar govori o tem , da smo delovali v zelo zahtevnih razmerah , ki so jih v veliki meri narekovale tako gospodarske in finančne razmere , ki pa so nastale v svetu , ne v Sloveniji , to moramo poudariti , seveda pa smo sestavni del tega dogajanja bili tudi v Sloveniji .',
 'In ukrepi , ki jih je bilo treba sprejemati v Državnem zboru , so bili zelo pomembni , da smo lahko obvladovali ravno to področje .',
 'Dosegli smo soglasje tako med opozicijo in koalicijo , zato da smo lahko spremenili v dveh bistvenih točkah tudi Ustavo Republike Slovenije in tudi na mednarodnem področju sprejeli pomembno odločitev , ko smo soglasno ratificirali vstop Republike Hrvaške v Evropsko unijo .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u3 Zahvaljujem se spoštovanemu gospodu Janku Vebru , predsedniku Državnega zbora , za izrečene besede .',
 'Hvala lepa .',
 'Začenjam 1. sejo Državnega zbora , ki jo je na podlagi 81. člena Ustave Republike Slovenije sklical predsednik Republike Slovenije , gospod Borut Pahor , ki bo Državni zbor zdaj tudi nagovoril .',
 'Prosim , spoštovani predsednik .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u4 Spoštovana gospa predsedujoča , spoštovane poslanke , spoštovani poslanci !',
 'Sprejmite najprej , prosim , moje iskrene čestitke za vašo izvolitev .',
 'Po običaju bi zdaj moral najbrž dodati željo , da se skupaj potrudimo po svojih najboljših močeh .',
 'Ampak , že dolgo časa ni več ta čas običajen , zato mi pride na misel Churchill .',
 'Trud po naših najboljših močeh ni več dovolj .',
 'Čas je , da naredimo pravo stvar .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u5 Predsedniku republike , spoštovanemu gospodu Borutu Pahorju , se zahvaljujem za njegove besede in hvala gospod predsednik , da ste počastili Državni zbor s svojo prisotnostjo .',
 'Hvala lepa .',
 'Obveščena sem , da se današnje seje ne more udeležiti poslanec gospod Luka Mesec .',
 'Na sejo Državnega zbora sta vabljena predsednik Državne volilne komisije Anton Gašper Frantar in direktor Službe državne volilne komisije Dušan Vučko , in sicer k 2. točki dnevnega reda .',
 'Vse prisotne še enkrat lepo pozdravljam !',
 'Pri vodenju seje Državnega zbora mi bosta pomagali generalna sekretarka državnega zbora , gospa Mojca Prelesnik , in namestnica generalne sekretarke , gospa Jerneja Bergoč .',
 'Prehajamo na določitev dnevnega reda prve seje Državnega zbora .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u33 Zahvaljujem se spoštovanemu dr. Miru Cerarju za podano obrazložitev predloga kandidata za predsednika Državnega zbora .',
 'Besedo dajem predstavnikom poslanskih skupin za predstavitev stališč .',
 'Besedo ima Poslanska skupina DeSUS , gospod Karl Viktor Erjavec .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u34 Hvala lepa .',
 'Najprej bi se zahvalil predsedujoči gospe Marjani Kotnik Poropat za odlično vodenje te seje .',
 'Čestitam .',
 'Čestitam seveda tudi vsem poslankam in poslancem na izvolitev in na potrditev mandata .',
 'V stranki DeSUS bomo kandidaturo dr. Milana Brgleza za predsednika Državnega zbora podprli .',
 'Podprli jo bomo zato , ker je nujno , da se Državni zbor čim prej konstituira in da čim prej pridemo tudi do vlade .',
 'Vemo , kakšna je situacija v državi , in ključno za reševanje problemov , s katerimi se sooča Slovenija , je stabilna politična situacija .',
 'ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u39 Hvala lepa .',
 'Besedo ima Poslanska skupina Nova Slovenija – krščanski demokrati .',
 'Spoštovana gospa Ljudmila Novak , izvolite .']

In [ ]:
target_sentences = df_renamed['translation'].to_list()
target_sentences

In [ ]:
target_tokenized_sentences = []

# Run the language processing on each sentence
for i in target_sentences:
    # Transform the output into a dictionary
    doc = nlp(i).to_dict()

    # Create a list of words in the current sentence
    current_sentence_list = []

    for sentence in doc:
        for word in sentence:
            # Add the word to the list of words for this sentence
            # print(word)
            current_sentence_list.append(word[0]['text'])

    # Join the list into a space-separated string to get tokenized text
    current_string = " ".join(current_sentence_list)

    # Add the tokenized sentence to a list of all sentences
    target_tokenized_sentences.append(current_string)

# Add the result to the df
df_renamed["translation_tokenized"] = target_tokenized_sentences

In [ ]:
word