## Text preparation

In [ ]:
# # Open the file with the source text and translation
# df = pd.read_csv("/kaggle/input/parlamintsample/Parlamint-SI-bigger-sample-translated.csv", sep="\t", index_col = 0)
# df.head(2)

,file,sentence_id,text,proper_nouns,length,translation
0,ParlaMint-SI_2019-10-23-SDZ8-Redna-12.ana.xml,ParlaMint-SI_2019-10-23-SDZ8-Redna-12.seg2.1,Začenjam nadaljevanje 12. seje Državnega zbor...,[],7,I am starting a continuation of the 12th meeti...
1,ParlaMint-SI_2019-10-23-SDZ8-Redna-12.ana.xml,ParlaMint-SI_2019-10-23-SDZ8-Redna-12.seg3.1,"Obveščen sem , da se današnje seje ne morejo u...","[{15: ['Eva', 'Eva'], 16: ['Irgl', 'Irgl'], 19...",89,I am informed that today's meeting cannot be a...

In [ ]:
# # As this is just a demostration, let's use only the first 100 sentences
# # and pretend that we do not have the information on proper_nouns yet
# df = df[:100]

# df = df.drop(columns=["proper_nouns"])
# df.describe(include="all")

In [1]:
import pandas as pd

df_csv = pd.read_csv("/content/sample_txt.csv")

In [4]:
df_csv.head()

,text,translation
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut..."
2,Lepo pozdravljena.,Nice to meet you.
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...
4,"Izvolite, prosim.","Here you go, please."

## Session 1

List of languages, covered by the Stanza models: https://stanfordnlp.github.io/stanza/ner_models.html

In [2]:
# Install and download the CLASSLA tool
!pip install -qU classla

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 159.2 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.9/249.9 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 42.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 8.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albucore 0.0.14 requires numpy>=1.24, but you have numpy 1.23.0 which is incompatible.
albumentations 1.4.14 requires numpy>=1.24.4, but you have numpy 1.23.0 which is incompatible.
chex 0.1.86 requires numpy>=1.24.1, but you have numpy 1.23.0 which is incompatible.
dopamine-rl 4.0.9 requires tqdm>=4.64.1, but you have tqdm 4.62.3 which is incompatible.
google-ai-generativelanguage 0.6.6 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-api-core 2.19.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-aiplatform 1.64.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-bigquery-connection 1.15.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-bigquery-storage 2.25.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-bigtable 2.26.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-datastore 2.19.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-firestore 2.16.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 4.21.2 which is incompatible.
google-cloud-functions 1.16.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-iam 2.15.2 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-language 2.13.4 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-pubsub 2.23.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-resource-manager 1.12.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-cloud-translate 3.15.5 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
google-colab 1.0.0 requires requests==2.32.3, but you have requests 2.28.0 which is incompatible.
googleapis-common-protos 1.65.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
grpc-google-iam-v1 0.13.1 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 4.21.2 which is incompatible.
pandas-stubs 2.1.4.231227 requires numpy>=1.26.0; python_version < "3.13", but you have numpy 1.23.0 which is incompatible.
tensorflow 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 1.23.0 which is incompatible.
tensorflow 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 4.21.2 which is incompatible.
tensorflow-metadata 1.15.0 requires protobuf<4.21,>=3.20.3; python_version < "3.11", but you have protobuf 4.21.2 which is incompatible.
torchaudio 2.4.0+cu121 requires torch==2.4.0, but you have torch 1.12.0 which is incompatible.
torchvision 0.19.0+cu121 requires torch==2.4.0, but you have torch 1.12.0 which is incompatible.
yfinance 0.2.43 requires requests>=2.31, but you have requests 2.28.0 which is incompatible.

In [3]:
import classla
classla.download('sl')
nlp = classla.Pipeline('sl', processors='tokenize,ner,pos,lemma')

/usr/local/lib/python3.10/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.20) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Downloading https://raw.githubusercontent.com/clarinsi/classla-resources/main/resources_2.1.json: 11.4kB [00:00, 18.0MB/s]
INFO:classla:Downloading these customized packages for language: sl (Slovenian)...
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| depparse  | standard |
| ner       | standard |
| pretrain  | standard |
========================

Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1767/suk_pos: 100%|██████████| 425M/425M [00:23<00:00, 17.9MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1768/suk_lemmatizer.pt: 100%|██████████| 2.19M/2.19M [00:01<00:00, 1.98MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1769/suk_udsyn: 100%|██████████| 90.6M/90.6M [00:05<00:00, 15.4MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1321/ssj500k: 100%|██████████| 48.3M/48.3M [00:03<00:00, 13.6MB/s]
Downloading https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1769/sl_ssj.pretrain.pt: 100%|██████████| 110M/110M [00:22<00:00, 4.92MB/s]
INFO:classla:Finished downloading models and saved to /root/classla_resources.
INFO:classla:Loading these models for language: sl (Slovenian):
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| ner       | standard |
========================

INFO:classla:Use device: cpu
INFO:classla:Loading: tokenize
INFO:classla:Loading: pos
INFO:classla:Loading: lemma
INFO:classla:Loading: ner
INFO:classla:Done loading processors!

In [ ]:
# Inspect how the output of the tool looks like.
doc = nlp("Hvala. Prehajam na novo točko.").to_dict()

for sentence in doc:
    print(sentence)

([{'id': 1, 'text': 'Hvala', 'lemma': 'hvala', 'upos': 'NOUN', 'xpos': 'Ncfsn', 'feats': 'Case=Nom|Gender=Fem|Number=Sing', 'misc': 'SpaceAfter=No', 'ner': 'O'}, {'id': 2, 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'Z', 'ner': 'O'}], '# newpar id = 1\n# sent_id = 1.1\n# text = Hvala.\n')
([{'id': 1, 'text': 'Prehajam', 'lemma': 'prehajati', 'upos': 'VERB', 'xpos': 'Vmpr1s', 'feats': 'Aspect=Imp|Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin', 'ner': 'O'}, {'id': 2, 'text': 'na', 'lemma': 'na', 'upos': 'ADP', 'xpos': 'Sa', 'feats': 'Case=Acc', 'ner': 'O'}, {'id': 3, 'text': 'novo', 'lemma': 'nov', 'upos': 'ADJ', 'xpos': 'Agpfsa', 'feats': 'Case=Acc|Degree=Pos|Gender=Fem|Number=Sing', 'ner': 'O'}, {'id': 4, 'text': 'točko', 'lemma': 'točka', 'upos': 'NOUN', 'xpos': 'Ncfsa', 'feats': 'Case=Acc|Gender=Fem|Number=Sing', 'misc': 'SpaceAfter=No', 'ner': 'O'}, {'id': 5, 'text': '.', 'lemma': '.', 'upos': 'PUNCT', 'xpos': 'Z', 'ner': 'O'}], '# sent_id = 1.2\n# text = Prehajam na novo točko.\n')

In [5]:
# Create a list of source texts
source_sentences = df_csv['text'].to_list()
len(source_sentences)

42

In [6]:
# Create a list of translation sentences
target_sentences = df_csv['translation'].to_list()

In [8]:
# Create a list of tokenized text where all words are separated by spaces
# this is needed for word alignment
tokenized_sentences = []

# Create a NER and lemma information into which you will save element for each sentence
proper_noun_list = []

# Run the processing on each sentence
for i in source_sentences:
    doc = nlp(i).to_dict()

    # Create a list of words in the current sentence
    current_sentence_list = []

    # Create a dictionary of all information on proper names for the current sentence
    word_dict = {}

    # Loop through the words in the sentence and add them to a current sentence list
    for sentence in doc:
        for word in sentence[0]:
            current_sentence_list.append(word["text"])

            # Find the current index - you need to substract 1 from the word index,
            # because indexing in the process starts with 1, not 0
            current_index = int(word["id"]) - 1

            # Add information on the lemma if the NE is personal name
            if "PER" in word["ner"]:
                word_dict[current_index] = [word["text"], word["lemma"]]

    # Join the list into a space-separated string to get tokenized text
    current_string = " ".join(current_sentence_list)

    tokenized_sentences.append(current_string)

    # Add the proper noun information for the current sentence to list for all sentences
    proper_noun_list.append(word_dict)

# Add the result to the df
df_csv["text_tokenized"] = tokenized_sentences
df_csv["proper_noun"] = proper_noun_list

In [9]:
# Display the results
with pd.option_context('display.max_colwidth', None):
  display(df_csv[["text", "text_tokenized", "proper_noun", "translation"]][:2])

,text,text_tokenized,proper_noun,translation
0,"ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoštovani, prosim, da zasedete svoja mesta.","ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u1 Spoštovani , prosim , da zasedete svoja mesta .",{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Please sit down.
1,"V naši sredini pozdravljam predsednika države, gospoda Boruta Pahorja in predsednika Državnega zbora, gospoda Janka Vebra.","V naši sredini pozdravljam predsednika države , gospoda Boruta Pahorja in predsednika Državnega zbora , gospoda Janka Vebra .","{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor'], 16: ['Janka', 'Janko'], 17: ['Vebra', 'Veber']}","I welcome the President of the State, Mr Borut Pahor and the President of the State Council, Mr Janka Webra."

If your language is not covered by CLASSLA, you can use Stanza - I will demonstrate how it works on the English translation.

In [10]:
!pip install -q stanza

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 990.1/990.1 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.4/431.4 kB 23.1 MB/s eta 0:00:00

In [11]:
import stanza

nlp = stanza.Pipeline(lang='en', processors='tokenize,mwt,pos,lemma, ner')

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.8.0.json:   0%|   …

INFO:stanza:Downloaded file to /root/stanza_resources/resources.json

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/tokenize/combined.pt:   0%|    …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/mwt/combined.pt:   0%|         …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/pos/combined_charlm.pt:   0%|  …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/lemma/combined_nocharlm.pt:   0…

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/ner/ontonotes-ww-multi_charlm.p…

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/backward_charlm/1billion.pt:   …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/pretrain/conll17.pt:   0%|     …

Downloading https://huggingface.co/stanfordnlp/stanza-en/resolve/v1.8.0/models/forward_charlm/1billion.pt:   0…

INFO:stanza:Loading these models for language: en (English):
=========================================
| Processor | Package                   |
-----------------------------------------
| tokenize  | combined                  |
| mwt       | combined                  |
| pos       | combined_charlm           |
| lemma     | combined_nocharlm         |
| ner       | ontonotes-ww-multi_charlm |
=========================================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: pos
INFO:stanza:Loading: lemma
INFO:stanza:Loading: ner
INFO:stanza:Done loading processors!

In [13]:
#Create a list of tokenized text where all words are separated by spaces - this is needed for word alignment
tokenized_sentences = []

# Create a NER and lemma information into which you will save element for each sentence
proper_noun_list = []

# Run the processing on each sentence
for i in target_sentences:
    doc = nlp(i).to_dict()

    # Create a list of words in the current sentence
    current_sentence_list = []

    # Create a dictionary of all information on proper names for the current sentence
    word_dict = {}

    # Loop through the words in the sentence and add them to a current sentence list
    for sentence in doc:
        for word in sentence:
            current_sentence_list.append(word["text"])

            # Find the current index - you need to substract 1 from the word index,
            # because indexing in the process starts with 1, not 0
            if isinstance(word["id"], tuple):
              current_index = int(word["id"][0])
            else:
              current_index = int(word["id"]) - 1

            # Add information on the lemma if the NE is personal name
            if "ner" in word.keys() and "lemma" in word.keys() and "PER" in word["ner"]:
                word_dict[current_index] = [word["text"], word["lemma"]]

    # Join the list into a space-separated string to get tokenized text
    current_string = " ".join(current_sentence_list)

    tokenized_sentences.append(current_string)

    # Add the proper noun information for the current sentence to list for all sentences
    proper_noun_list.append(word_dict)

# Add the result to the df
df_csv["En_text_tokenized"] = tokenized_sentences
df_csv["En_proper_noun"] = proper_noun_list

In [14]:
df_csv.head()

,text,translation,text_tokenized,proper_noun,En_text_tokenized,En_proper_noun
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{}
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...",V naši sredini pozdravljam predsednika države ...,"{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor...","I welcome the President of the State , Mr Boru...","{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']..."
2,Lepo pozdravljena.,Nice to meet you.,Lepo pozdravljena .,{},Nice to meet you .,{}
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoš...,"{18: ['Janku', 'Janko'], 19: ['Vebru', 'Veber']}",I give the floor to the respected President of...,"{14: ['Janku', 'Janku'], 15: ['Vebru', 'Vebru']}"
4,"Izvolite, prosim.","Here you go, please.","Izvolite , prosim .",{},"Here you go , please .",{}

If we want to apply Stanza to the translation to only get the tokenized text:

In [15]:
# Create a list of tokenized text where all words are separated by spaces
# This is needed for word alignment
target_tokenized_sentences = []

# Run the language processing on each sentence
for i in target_sentences:
    # Transform the output into a dictionary
    doc = nlp(i).to_dict()

    # Create a list of words in the current sentence
    current_sentence_list = []

    # Loop through the words in the sentence
    # and add them to a current sentence list
    # to get tokenized sentences
    for sentence in doc:
        for word in sentence:
            current_sentence_list.append(word["text"])

    # Join the list into a space-separated string to get tokenized text
    current_string = " ".join(current_sentence_list)

    target_tokenized_sentences.append(current_string)

# Add the result to the df
df_csv["translation_tokenized"] = target_tokenized_sentences

In [16]:
# Display the results
with pd.option_context('display.max_colwidth', None):
  display(df_csv[["text", "text_tokenized", "proper_noun", "translation", "translation_tokenized"]][:2])

,text,text_tokenized,proper_noun,translation,translation_tokenized
0,"ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoštovani, prosim, da zasedete svoja mesta.","ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna - 01 . u1 Spoštovani , prosim , da zasedete svoja mesta .",{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Please sit down.,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Please sit down .
1,"V naši sredini pozdravljam predsednika države, gospoda Boruta Pahorja in predsednika Državnega zbora, gospoda Janka Vebra.","V naši sredini pozdravljam predsednika države , gospoda Boruta Pahorja in predsednika Državnega zbora , gospoda Janka Vebra .","{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor'], 16: ['Janka', 'Janko'], 17: ['Vebra', 'Veber']}","I welcome the President of the State, Mr Borut Pahor and the President of the State Council, Mr Janka Webra.","I welcome the President of the State , Mr Borut Pahor and the President of the State Council , Mr Janka Webra ."

## Apply word alignments with eflomal

In [17]:
# Install eflomal
!git clone https://github.com/robertostling/eflomal
%cd /content/eflomal
!make
!sudo make install
!python3 setup.py install

Cloning into 'eflomal'...
remote: Enumerating objects: 316, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 316 (delta 83), reused 73 (delta 68), pack-reused 210 (from 1)
Receiving objects: 100% (316/316), 122.61 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (153/153), done.
/content/eflomal
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Compiling python/eflomal/eflomal.pyx because it changed.
[1/1] Cythonizing python/eflomal/eflomal.pyx
/usr/local/lib/python3.10/dist-packages/setuptools/dist.py:300: InformationOnly: Normalizing '1.0.0-beta2' to '1.0.0b2'
  self.metadata.version = self._normalize_version(self.metadata.version)
running install
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating python/eflomal.egg-info
writing python/eflomal.egg-info/PKG-INFO
writing dependency_links to python/eflomal.egg-info/dependency_links.txt
writing requirements to python/eflomal.egg-info/requires.txt
writing top-level names to python/eflomal.egg-info/top_level.txt
writing manifest file 'python/eflomal.egg-info/SOURCES.txt'
dependency /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/arrayobject.h won't be automatically included in the manifest: the path must be relative
dependency /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/arrayscalars.h won't be automatically included in the manifest: the path must be relative
dependency /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/ndarrayobject.h won't be automatically included in the manifest: the path must be relative
dependency /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/ndarraytypes.h won't be automatically included in the manifest: the path must be relative
dependency /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/ufuncobject.h won't be automatically included in the manifest: the path must be relative
reading manifest file 'python/eflomal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'python/eflomal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
make: Entering directory '/content/eflomal/src'
cc -Ofast -march=native -Wall --std=gnu99 -Wno-unused-function -g -fopenmp -c eflomal.c
eflomal.c: In function ‘text_alignment_load_priors’:
eflomal.c:858:54: warning: dereferencing type-punned pointer will break strict-aliasing rules []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstrict-aliasing-Wstrict-aliasing]8;;]
  858 |         map_token_u32_add(ta->source_prior + e, f, *((uint32_t*)&alpha));
      |                                                     ~^~~~~~~~~~~~~~~~~~
In file included from eflomal.c:53:
random.c: In function ‘random_system_state’:
random.c:73:5: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
   73 |     fread(state, sizeof(*state), 1, file);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -lm -lgomp -fopenmp  eflomal.o   -o eflomal
make: Leaving directory '/content/eflomal/src'
make: Entering directory '/content/eflomal/src'
mkdir -p ../python/eflomal/bin
cp eflomal ../python/eflomal/bin
make: Leaving directory '/content/eflomal/src'
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/eflomal
copying python/eflomal/__init__.py -> build/lib.linux-x86_64-cpython-310/eflomal
creating build/lib.linux-x86_64-cpython-310/eflomal/bin
copying python/eflomal/bin/eflomal -> build/lib.linux-x86_64-cpython-310/eflomal/bin
running build_ext
building 'eflomal.cython' extension
creating build/temp.linux-x86_64-cpython-310
creating build/temp.linux-x86_64-cpython-310/python
creating build/temp.linux-x86_64-cpython-310/python/eflomal
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.10/dist-packages/numpy/core/include -I/usr/include/python3.10 -c python/eflomal/eflomal.c -o build/temp.linux-x86_64-cpython-310/python/eflomal/eflomal.o
In file included from /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1948,
                 from /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from python/eflomal/eflomal.c:1268:
/usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
python/eflomal/eflomal.c: In function ‘__pyx_f_7eflomal_6cython_write_text’:
python/eflomal/eflomal.c:6206:46: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘Py_ssize_t’ {aka ‘long int’} []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wformat=-Wformat=]8;;]
 6206 |   (void)(fprintf(__pyx_v_f, ((char const *)"%d %d\n"), __pyx_t_6, __pyx_v_voc_size));
      |                                             ~^         ~~~~~~~~~
      |                                              |         |
      |                                              int       Py_ssize_t {aka long int}
      |                                             %ld
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-310/python/eflomal/eflomal.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-310/eflomal/cython.cpython-310-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/eflomal
copying build/lib.linux-x86_64-cpython-310/eflomal/__init__.py -> build/bdist.linux-x86_64/egg/eflomal
creating build/bdist.linux-x86_64/egg/eflomal/bin
copying build/lib.linux-x86_64-cpython-310/eflomal/bin/eflomal -> build/bdist.linux-x86_64/egg/eflomal/bin
copying build/lib.linux-x86_64-cpython-310/eflomal/cython.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/eflomal
byte-compiling build/bdist.linux-x86_64/egg/eflomal/__init__.py to __init__.cpython-310.pyc
creating stub loader for eflomal/cython.cpython-310-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/eflomal/cython.py to cython.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.10
copying and adjusting python/scripts/eflomal-align -> build/scripts-3.10
copying and adjusting python/scripts/eflomal-makepriors -> build/scripts-3.10
changing mode of build/scripts-3.10/eflomal-align from 644 to 755
changing mode of build/scripts-3.10/eflomal-makepriors from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/eflomal-makepriors -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/eflomal-align -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/eflomal-makepriors to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/eflomal-align to 755
copying python/eflomal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/eflomal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/eflomal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/eflomal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying python/eflomal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
eflomal.__pycache__.cython.cpython-310: module references __file__
creating dist
creating 'dist/eflomal-1.0.0b2-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing eflomal-1.0.0b2-py3.10-linux-x86_64.egg
creating /usr/local/lib/python3.10/dist-packages/eflomal-1.0.0b2-py3.10-linux-x86_64.egg
Extracting eflomal-1.0.0b2-py3.10-linux-x86_64.egg to /usr/local/lib/python3.10/dist-packages
Adding eflomal 1.0.0b2 to easy-install.pth file
Installing eflomal-makepriors script to /usr/local/bin
Installing eflomal-align script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/eflomal-1.0.0b2-py3.10-linux-x86_64.egg
Processing dependencies for eflomal==1.0.0b2
Searching for Cython==3.0.11
Best match: Cython 3.0.11
Adding Cython 3.0.11 to easy-install.pth file
detected new path './eflomal-1.0.0b2-py3.10-linux-x86_64.egg'
Installing cygdb script to /usr/local/bin
Installing cython script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Using /usr/local/lib/python3.10/dist-packages
Searching for numpy==1.23.0
Best match: numpy 1.23.0
Adding numpy 1.23.0 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.10 script to /usr/local/bin

Using /usr/local/lib/python3.10/dist-packages
Finished processing dependencies for eflomal==1.0.0b2

In [18]:
# Create files for all texts and all translations

Slovene_sentences = open("Slovene_sentences.txt", "w")
English_sentences = open("English_sentences.txt", "w")

for i in df_csv.text_tokenized.to_list():
	Slovene_sentences.write(i)
	Slovene_sentences.write("\n")

for i in df_csv.translation_tokenized.to_list():
	English_sentences.write(i)
	English_sentences.write("\n")

Slovene_sentences.close()
English_sentences.close()

In [20]:
# Align sentences with eflomal
!python3 /content/eflomal/python/scripts/eflomal-align -s "/content/eflomal/Slovene_sentences.txt" -t "/content/eflomal/English_sentences.txt" --model 3 -f sl-en.fwd -r sl-en.rev

In [22]:
# Get list of alignments from the eflomal's output
# Create a list with each line as a separate element
aligns_list = open("/content/eflomal/sl-en.rev", "r").readlines()

# Replace the \n element at the end of lines
aligns_list = [i.replace("\n", "") for i in aligns_list]

# Split each line into a list of alignment pairs: ["0-1", "1-2", "2-3"]
aligns_list = [i.split(" ") for i in aligns_list]

# Create a list to save the alignment dictionaries to
final_aligns = []

for i in aligns_list:
    # Create a dictionary for each sentence (each line)
    current_line = {}

    # For each alignment pair in line:
    for element in i:
        # Split the string "1-2" into a list of ["1", "2"]
        new_list = element.split("-")

        # Convert the strings to integers
        # and save a dictionary with the source word as key
        # and translated word as the value
        current_line[int(new_list[0])] = int(new_list[1])

    #Add the dictionary for each sentence to the list of all dictionaries
    final_aligns.append(current_line)

# Show result
print(final_aligns[:2])
# Output:
# [{0: 0, 1: 1, 2: 4, 3: 5, 4: 6, 6: 7, 7: 8, 9: 9, 10: 10, 11: 11}, {0: 2, 1: 3, 2: 4, 3: 5, 4: 6}]

# Add a to the df
df_csv["alignments"] = final_aligns

[{1: 0, 5: 0, 7: 0, 8: 0, 9: 1, 11: 0, 14: 0, 16: 1, 17: 2, 18: 0, 19: 1, 22: 2, 23: 2, 24: 3, 25: 4}, {1: 1, 2: 1, 3: 2, 4: 3, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22}]

In [23]:
df_csv.head(1)

,text,translation,text_tokenized,proper_noun,En_text_tokenized,En_proper_noun,translation_tokenized,alignments
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,"{1: 0, 5: 0, 7: 0, 8: 0, 9: 1, 11: 0, 14: 0, 1..."

In [ ]:
#df.head(1)

,file,sentence_id,text,length,translation,text_tokenized,proper_noun,translation_tokenized,alignments
0,ParlaMint-SI_2019-10-23-SDZ8-Redna-12.ana.xml,ParlaMint-SI_2019-10-23-SDZ8-Redna-12.seg2.1,Začenjam nadaljevanje 12. seje Državnega zbor...,7,I am starting a continuation of the 12th meeti...,Začenjam nadaljevanje 12. seje Državnega zbora .,{},I am starting a continuation of the 12th meeti...,"{0: 1, 1: 4, 2: 7, 3: 8, 4: 11, 5: 12, 6: 13}"

In [24]:
# Substitute words in the translation based on alignments

# Create a list of tokenized translation, dictionary of proper nouns
# and alignments for each sentence pair
main_info = list(zip(df_csv["translation_tokenized"], df_csv["proper_noun"], df_csv["alignments"]))

# Create lists for the new translations and information on what was substituted
new_translations = []
substituted_only = []

# Add information whether an error occurred
error_list = []

# Loop through information for each sentence
for i in main_info:
    # Create a list of substitutions for current sentence
    current_substituted_only = []
    # Save error as No
    current_error = "No"

    # Take the relevant info for this sentence
    # from the main_info list
    current_translation = i[0]
    proper_noun_dict = i[1]
    alignments = i[2]

# If no proper names were detected, do not change the translation
    if proper_noun_dict == 0:
        new_translations.append(current_translation)

    else:
    # Else, substitute the word with the Slovene lemma based on the index - loop through the proper nouns in the dictionary to be changed
        for source_word_index in list(proper_noun_dict.keys()):
            try:
                # split the translation into list of words
                word_list = current_translation.split()

                # Get index of the translated word from the alignment dict
                translated_word_index = alignments[source_word_index]

                # Get the lemma to substitute the translated word with
                correct_lemma = proper_noun_dict[source_word_index][1]

                # If the translated word and lemma are not the same, get substituted word and its match
                if word_list[translated_word_index] != correct_lemma:

                    # Add the information that the word was substituted and with word it was substituted
                    current_substituted_only.append((word_list[translated_word_index], correct_lemma))

                  # Substitute the word in the translation word list
                 #  with the lemma based on its index
                    word_list[translated_word_index] = correct_lemma

                # After looping through proper names in the dict,
                # change the translation by merging the words back into a string
                current_translation = " ".join(word_list)

            # If the eflomal tool was not sure, it did not align a word
            # This can lead to errors, which we will save to the output
            except:
                current_error = f"Issue: index {word_index}: {i[1][word_index]}"

    # After the loop through proper nouns, save the new translation
    new_translations.append(current_translation)

  # Add information on what was substituted
    substituted_only.append(current_substituted_only)
    error_list.append(current_error)

# Add the lists to the df
df_csv["new_translations"] = new_translations
df_csv["substituted_words"] = substituted_only
df_csv["errors"] = error_list

In [25]:
df_csv.columns

Index(['text', 'translation', 'text_tokenized', 'proper_noun',
       'En_text_tokenized', 'En_proper_noun', 'translation_tokenized',
       'alignments', 'new_translations', 'substituted_words', 'errors'],
      dtype='object')

In [26]:
df_csv[['text','text_tokenized','proper_noun', 'translation',
       'translation_tokenized', 'alignments',
      'new_translations', 'substituted_words', 'errors']].head()

,text,text_tokenized,proper_noun,translation,translation_tokenized,alignments,new_translations,substituted_words,errors
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,"{1: 0, 5: 0, 7: 0, 8: 0, 9: 1, 11: 0, 14: 0, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,[],No
1,"V naši sredini pozdravljam predsednika države,...",V naši sredini pozdravljam predsednika države ...,"{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor...","I welcome the President of the State, Mr Borut...","I welcome the President of the State , Mr Boru...","{1: 1, 2: 1, 3: 2, 4: 3, 5: 6, 6: 7, 7: 8, 8: ...","I welcome the President of the State , Mr Boru...","[(Janka, Janko), (Webra, Veber)]",No
2,Lepo pozdravljena.,Lepo pozdravljena .,{},Nice to meet you.,Nice to meet you .,"{0: 0, 1: 2, 2: 4}",Nice to meet you .,[],No
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoš...,"{18: ['Janku', 'Janko'], 19: ['Vebru', 'Veber']}",I give the floor to the respected President of...,I give the floor to the respected President of...,"{0: 0, 1: 2, 2: 3, 3: 1, 4: 1, 5: 0, 6: 14, 7:...",I give the floor to the respected President of...,"[(Janku, Janko), (Vebru, Veber)]",No
4,"Izvolite, prosim.","Izvolite , prosim .",{},"Here you go, please.","Here you go , please .","{0: 0, 1: 3, 2: 4, 3: 5}","Here you go , please .",[],No

In [ ]:
#df.columns

Index(['file', 'sentence_id', 'text', 'length', 'translation',
       'text_tokenized', 'proper_noun', 'translation_tokenized', 'alignments',
       'new_translations', 'substituted_words', 'errors'],
      dtype='object')

In [ ]:
#df[['text','text_tokenized','proper_noun', 'translation',
#        'translation_tokenized', 'alignments',
#       'new_translations', 'substituted_words', 'errors']].head()

,text,text_tokenized,proper_noun,translation,translation_tokenized,alignments,new_translations,substituted_words,errors
0,Začenjam nadaljevanje 12. seje Državnega zbor...,Začenjam nadaljevanje 12. seje Državnega zbora .,{},I am starting a continuation of the 12th meeti...,I am starting a continuation of the 12th meeti...,"{0: 1, 1: 4, 2: 7, 3: 8, 4: 11, 5: 12, 6: 13}",I am starting a continuation of the 12th meeti...,[],No
1,"Obveščen sem , da se današnje seje ne morejo u...","Obveščen sem , da se današnje seje ne morejo u...","{15: ['Eva', 'Eva'], 16: ['Irgl', 'Irgl'], 20:...",I am informed that today's meeting cannot be a...,I am informed that today 's meeting cannot be ...,"{0: 0, 1: 2, 3: 3, 5: 4, 6: 6, 7: 7, 8: 9, 9: ...",I am informed that today 's meeting cannot be ...,"[(Vrtovac, Vrtovec), (Violeta, Jožef), (17:00,...",No
2,Vsem prisotnim še enkrat lep pozdrav !,Vsem prisotnim še enkrat lep pozdrav !,{},I'm here to say hello again!,I 'm here to say hello again !,"{0: 0, 1: 1, 3: 4, 4: 5, 5: 6, 6: 7}",I 'm here to say hello again !,[],No
3,"Prehajamo na 2. , 3. , 4. IN 5. TOČKO DNEVNEGA...","Prehajamo na 2 . , 3 . , 4 . IN 5 . TOČKO DNEV...",{},"Moving to 2, 3, 4. AND 5. DETECTION OF THE DAY...","Moving to 2 , 3 , 4 . AND 5 . DETECTION OF THE...","{0: 0, 1: 1, 2: 2, 4: 3, 5: 4, 7: 5, 8: 6, 9: ...","Moving to 2 , 3 , 4 . AND 5 . DETECTION OF THE...",[],No
4,Predloge zakonov je v obravnavo Državnemu zbo...,Predloge zakonov je v obravnavo Državnemu zbor...,{},Proposals for laws were submitted by the Gover...,Proposals for laws were submitted by the Gover...,"{0: 0, 1: 2, 4: 7, 5: 8, 6: 10, 7: 11, 8: 13, ...",Proposals for laws were submitted by the Gover...,[],No

In [27]:
# See some of the substitutions
df_csv[df_csv["substituted_words"] != "[]"].substituted_words.value_counts()[:80]

substituted_words
[]                                                                           30
[(Janku, Janko), (Vebru, Veber)]                                              2
[(Janka, Janko), (Webra, Veber)]                                              1
[(mind, Churchill)]                                                           1
[(Pahoru, Pahor)]                                                             1
[(Luka, luka)]                                                                1
[(Gashper, Anton), (Anton, Gašper), (Frontar, Frantar), (Service, Vučko)]     1
[(Jernej, Jerneja), (Bergoch, Bergoč)]                                        1
[(Mira, Miro), (Ceraru, Cerar)]                                               1
[(Marjani, Marjana), (Propopat, Poropat)]                                     1
[(Brglez's, Milan)]                                                           1
[(Lüdmila, Ljudmila)]                                                         1
Name: count, dtype: int64

In [30]:
# Save the df
df_csv.to_csv("Corrected-translation.csv")

In [29]:
df_csv

,text,translation,text_tokenized,proper_noun,En_text_tokenized,En_proper_noun,translation_tokenized,alignments,new_translations,substituted_words,errors
0,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,"{1: 0, 5: 0, 7: 0, 8: 0, 9: 1, 11: 0, 14: 0, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u1 Pleas...,[],No
1,"V naši sredini pozdravljam predsednika države,...","I welcome the President of the State, Mr Borut...",V naši sredini pozdravljam predsednika države ...,"{8: ['Boruta', 'Borut'], 9: ['Pahorja', 'Pahor...","I welcome the President of the State , Mr Boru...","{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']...","I welcome the President of the State , Mr Boru...","{1: 1, 2: 1, 3: 2, 4: 3, 5: 6, 6: 7, 7: 8, 8: ...","I welcome the President of the State , Mr Boru...","[(Janka, Janko), (Webra, Veber)]",No
2,Lepo pozdravljena.,Nice to meet you.,Lepo pozdravljena .,{},Nice to meet you .,{},Nice to meet you .,"{0: 0, 1: 2, 2: 4}",Nice to meet you .,[],No
3,[[aplavz]] [[himna]] Besedo dajem spoštovanemu...,I give the floor to the respected President of...,[ [ aplavz ] ] [ [ himna ] ] Besedo dajem spoš...,"{18: ['Janku', 'Janko'], 19: ['Vebru', 'Veber']}",I give the floor to the respected President of...,"{14: ['Janku', 'Janku'], 15: ['Vebru', 'Vebru']}",I give the floor to the respected President of...,"{0: 0, 1: 2, 2: 3, 3: 1, 4: 1, 5: 0, 6: 14, 7:...",I give the floor to the respected President of...,"[(Janku, Janko), (Vebru, Veber)]",No
4,"Izvolite, prosim.","Here you go, please.","Izvolite , prosim .",{},"Here you go , please .",{},"Here you go , please .","{0: 0, 1: 3, 2: 4, 3: 5}","Here you go , please .",[],No
5,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2\tHval...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,"{1: 0, 5: 0, 7: 0, 8: 1, 9: 0, 10: 1, 11: 0, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u2 Thank...,[],No
6,"Spoštovani predsednik Republike Slovenije, gos...",Respected President of the Republic of Sloveni...,"Spoštovani predsednik Republike Slovenije , go...","{6: ['Borut', 'Borut'], 7: ['Pahor', 'Pahor']}",Respected President of the Republic of Sloveni...,"{9: ['Borut', 'Borut'], 10: ['Pahor', 'Pahor']}",Respected President of the Republic of Sloveni...,"{0: 0, 1: 1, 2: 4, 3: 6, 4: 7, 5: 8, 6: 9, 7: ...",Respected President of the Republic of Sloveni...,[],No
7,"Dovolite mi, da vas nagovorim ob izteku VI.",Let me talk to you at the VI race.,"Dovolite mi , da vas nagovorim ob izteku VI .",{},Let me talk to you at the VI race .,{},Let me talk to you at the VI race .,"{0: 0, 1: 1, 4: 2, 5: 5, 6: 5, 7: 7, 8: 8, 9: 9}",Let me talk to you at the VI race .,[],No
8,mandata Državnega zbora.,The mandate of the State Council.,mandata Državnega zbora .,{},The mandate of the State Council .,{},The mandate of the State Council .,"{0: 1, 1: 4, 2: 5, 3: 6}",The mandate of the State Council .,[],No
9,"Mandat se izteka prej, kot določa Ustava, kar ...","The mandate is preceded by, as laid down in th...","Mandat se izteka prej , kot določa Ustava , ka...",{},"The mandate is preceded by , as laid down in t...",{},"The mandate is preceded by , as laid down in t...","{0: 2, 2: 3, 3: 6, 4: 5, 5: 7, 6: 7, 7: 8, 9: ...","The mandate is preceded by , as laid down in t...",[],No
10,"In ukrepi, ki jih je bilo treba sprejemati v D...",And the measures to be taken in the State Asse...,"In ukrepi , ki jih je bilo treba sprejemati v ...",{},And the measures to be taken in the State Asse...,{},And the measures to be taken in the State Asse...,"{0: 0, 1: 2, 3: 2, 4: 2, 5: 25, 6: 2, 7: 4, 8:...",And the measures to be taken in the State Asse...,[],No
11,Dosegli smo soglasje tako med opozicijo in koa...,We have reached agreement in this way between ...,Dosegli smo soglasje tako med opozicijo in koa...,{},We have reached agreement in this way between ...,{},We have reached agreement in this way between ...,"{0: 0, 1: 1, 2: 2, 3: 5, 4: 7, 5: 8, 6: 9, 7: ...",We have reached agreement in this way between ...,[],No
12,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u3\tZahv...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u3 I tha...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,"{21: ['Janku', 'Janko'], 22: ['Vebru', 'Veber']}",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u3 I tha...,"{3: ['Janku', 'Janku'], 4: ['Vebru', 'Vebru']}",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u3 I tha...,"{0: 0, 1: 1, 4: 2, 8: 2, 9: 1, 10: 2, 11: 1, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u3 I tha...,"[(Janku, Janko), (Vebru, Veber)]",No
13,Hvala lepa.,Thank you very much.,Hvala lepa .,{},Thank you very much .,{},Thank you very much .,"{0: 2, 1: 3, 2: 4}",Thank you very much .,[],No
14,"Začenjam 1. sejo Državnega zbora, ki jo je na ...","I start the 1st meeting of the State Assembly,...","Začenjam 1. sejo Državnega zbora , ki jo je na...","{22: ['Borut', 'Borut'], 23: ['Pahor', 'Pahor']}",I start the 1st meeting of the State Assembly ...,"{32: ['Borut', 'Borut'], 33: ['Pahor', 'Pahor']}",I start the 1st meeting of the State Assembly ...,"{0: 1, 1: 3, 2: 4, 3: 7, 4: 8, 5: 9, 6: 10, 7:...",I start the 1st meeting of the State Assembly ...,[],No
15,"Prosim, spoštovani predsednik.","Please, the respected President.","Prosim , spoštovani predsednik .",{},"Please , the respected President .",{},"Please , the respected President .","{0: 0, 1: 1, 2: 3, 3: 4, 4: 5}","Please , the respected President .",[],No
16,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u4\tSpoš...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u4 Madam...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u4 Madam...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u4 Madam...,"{1: 0, 5: 0, 7: 0, 8: 1, 9: 0, 11: 0, 13: 0, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u4 Madam...,[],No
17,"Sprejmite najprej, prosim, moje iskrene čestit...","First, please accept my sincere congratulation...","Sprejmite najprej , prosim , moje iskrene čest...",{},"First , please accept my sincere congratulatio...",{},"First , please accept my sincere congratulatio...","{1: 0, 2: 1, 3: 2, 5: 3, 6: 4, 7: 5, 8: 6, 9: ...","First , please accept my sincere congratulatio...",[],No
18,"Po običaju bi zdaj moral najbrž dodati željo, ...","Naturally, now more than ever before, we shoul...","Po običaju bi zdaj moral najbrž dodati željo ,...",{},"Naturally , now more than ever before , we sho...",{},"Naturally , now more than ever before , we sho...","{0: 0, 1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 6, 7: ...","Naturally , now more than ever before , we sho...",[],No
19,"Ampak, že dolgo časa ni več ta čas običajen, z...",But because for a long time this time is no lo...,"Ampak , že dolgo časa ni več ta čas običajen ,...","{16: ['Churchill', 'Churchill']}",But because for a long time this time is no lo...,"{22: ['Churchill', 'Churchill']}",But because for a long time this time is no lo...,"{0: 0, 2: 0, 3: 1, 4: 10, 5: 6, 6: 16, 7: 14, ...",But because for a long time this time is no lo...,"[(mind, Churchill)]",No
20,Trud po naših najboljših močeh ni več dovolj.,Hard enough for our best powers.,Trud po naših najboljših močeh ni več dovolj .,{},Hard enough for our best powers .,{},Hard enough for our best powers .,"{0: 0, 1: 1, 2: 1, 3: 4, 4: 3, 5: 3, 6: 5, 7: ...",Hard enough for our best powers .,[],No
21,"Čas je, da naredimo pravo stvar.",It's time to do the right thing.,"Čas je , da naredimo pravo stvar .",{},It's It 's time to do the right thing .,{},It's It 's time to do the right thing .,"{0: 2, 1: 3, 4: 5, 5: 7, 6: 8, 7: 9}",It's It 's time to do the right thing .,[],No
22,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u5\tPred...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u5 I tha...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,"{22: ['Borutu', 'Borut'], 23: ['Pahorju', 'Pah...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u5 I tha...,"{9: ['Borut', 'Borut'], 10: ['Pahoru', 'Pahoru']}",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u5 I tha...,"{1: 1, 5: 1, 7: 1, 8: 2, 9: 1, 10: 2, 11: 1, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u5 I tha...,"[(Pahoru, Pahor)]",No
23,Hvala lepa.,Thank you very much.,Hvala lepa .,{},Thank you very much .,{},Thank you very much .,"{0: 2, 1: 3, 2: 4}",Thank you very much .,[],No
24,"Obveščena sem, da se današnje seje ne more ude...",I am informed that today's meeting cannot be a...,"Obveščena sem , da se današnje seje ne more ud...","{12: ['Luka', 'luka'], 13: ['Mesec', 'Mesec']}",I am informed that today's today 's meeting ca...,"{13: ['Luka', 'Luka'], 14: ['Mesec', 'Mesec']}",I am informed that today's today 's meeting ca...,"{0: 1, 1: 2, 3: 4, 5: 5, 6: 7, 7: 10, 8: 11, 9...",I am informed that today's today 's meeting ca...,"[(Luka, luka)]",No
25,Na sejo Državnega zbora sta vabljena predsedni...,"At the meeting of the National Assembly, the P...",Na sejo Državnega zbora sta vabljena predsedni...,"{10: ['Anton', 'Anton'], 11: ['Gašper', 'Gašpe...","At the meeting of the National Assembly , the ...","{16: ['Anton', 'Anton'], 17: ['Gashper', 'Gash...","At the meeting of the National Assembly , the ...","{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 14, 6: 16, 7...","At the meeting of the National Assembly , the ...","[(Gashper, Anton), (Anton, Gašper), (Frontar, ...",No
26,Vse prisotne še enkrat lepo pozdravljam!,I'll say hello again!,Vse prisotne še enkrat lepo pozdravljam !,{},I'll I 'll say hello again !,{},I'll I 'll say hello again !,"{0: 0, 1: 0, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}",I'll I 'll say hello again !,[],No
27,Pri vodenju seje Državnega zbora mi bosta poma...,At the holding of the meeting of the State Ass...,Pri vodenju seje Državnega zbora mi bosta poma...,"{14: ['Mojca', 'Mojca'], 15: ['Prelesnik', 'Pr...",At the holding of the meeting of the State Ass...,"{26: ['Mojca', 'Mojca'], 27: ['Prelesnik', 'Pr...",At the holding of the meeting of the State Ass...,"{0: 2, 1: 2, 2: 5, 3: 8, 4: 9, 5: 14, 6: 15, 7...",At the holding of the meeting of the State Ass...,"[(Jernej, Jerneja), (Bergoch, Bergoč)]",No
28,Prehajamo na določitev dnevnega reda prve seje...,We are going to set the agenda for the first m...,Prehajamo na določitev dnevnega reda prve seje...,{},We are going to set the agenda for the first m...,{},We are going to set the agenda for the first m...,"{0: 2, 1: 3, 2: 4, 3: 5, 4: 6, 5: 9, 6: 10, 7:...",We are going to set the agenda for the first m...,[],No
29,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u33\tZah...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u33 I th...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,"{21: ['Miru', 'Miro'], 22: ['Cerarju', 'Cerar']}",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u33 I th...,"{5: ['Mira', 'Mira'], 6: ['Ceraru', 'Ceraru']}",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u33 I th...,"{0: 0, 1: 1, 5: 1, 7: 1, 8: 2, 9: 1, 10: 2, 11...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u33 I th...,"[(Mira, Miro), (Ceraru, Cerar)]",No
30,Besedo dajem predstavnikom poslanskih skupin z...,I give the floor to the representatives of the...,Besedo dajem predstavnikom poslanskih skupin z...,{},I give the floor to the representatives of the...,{},I give the floor to the representatives of the...,"{0: 2, 1: 3, 2: 6, 3: 9, 4: 10, 5: 11, 6: 12, ...",I give the floor to the representatives of the...,[],No
31,"Besedo ima Poslanska skupina DeSUS, gospod Kar...","The word has a delegation group DeSUS, Mr. Kar...","Besedo ima Poslanska skupina DeSUS , gospod Ka...","{7: ['Karl', 'Karl'], 8: ['Viktor', 'Viktor'],...","The word has a delegation group DeSUS , Mr. Ka...","{9: ['Karl', 'Karl'], 10: ['Viktor', 'Viktor']...","The word has a delegation group DeSUS , Mr. Ka...","{0: 0, 1: 1, 2: 2, 3: 5, 4: 6, 5: 7, 6: 8, 7: ...","The word has a delegation group DeSUS , Mr. Ka...",[],No
32,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u34\tHva...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u34 Than...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u34 Than...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u34 Than...,"{1: 0, 4: 2, 5: 0, 8: 2, 9: 0, 10: 1, 11: 1, 1...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u34 Than...,[],No
33,Najprej bi se zahvalil predsedujoči gospe Marj...,"First of all, I would like to thank the Presid...",Najprej bi se zahvalil predsedujoči gospe Marj...,"{6: ['Marjani', 'Marjana'], 7: ['Kotnik', 'Kot...","First of all , I would like to thank the Presi...",{},"First of all , I would like to thank the Presi...","{0: 0, 1: 3, 3: 5, 4: 6, 5: 14, 6: 17, 7: 18, ...","First of all , I would like to thank the Presi...","[(Marjani, Marjana), (Propopat, Poropat)]",No
34,Čestitam.,Congratulations.,Čestitam .,{},Congratulations .,{},Congratulations .,"{0: 0, 1: 1}",Congratulations .,[],No
35,Čestitam seveda tudi vsem poslankam in poslanc...,"Of course, I congratulate all the Members and ...",Čestitam seveda tudi vsem poslankam in poslanc...,{},"Of course , I congratulate all the Members and...",{},"Of course , I congratulate all the Members and...","{0: 1, 1: 1, 3: 4, 4: 7, 5: 8, 6: 9, 7: 11, 8:...","Of course , I congratulate all the Members and...",[],No
36,V stranki DeSUS bomo kandidaturo dr. Milana Br...,"In the DeSUS website, we will support Dr. Mila...",V stranki DeSUS bomo kandidaturo dr. Milana Br...,"{6: ['Milana', 'Milan'], 7: ['Brgleza', 'Brgle...","In the DeSUS website , we will support Dr. Mil...","{9: ['Milan', 'Milan']}","In the DeSUS website , we will support Dr. Mil...","{0: 0, 1: 1, 2: 2, 3: 7, 4: 8, 5: 8, 6: 10, 7:...","In the DeSUS website , we will support Dr. Mil...","[(Brglez's, Milan)]",No
37,"Podprli jo bomo zato, ker je nujno, da se Drža...",We will support it because it is necessary tha...,"Podprli jo bomo zato , ker je nujno , da se Dr...",{},We will support it because it is necessary tha...,{},We will support it because it is necessary tha...,"{0: 1, 1: 1, 2: 2, 3: 3, 5: 5, 6: 6, 7: 7, 8: ...",We will support it because it is necessary tha...,[],No
38,"Vemo, kakšna je situacija v državi, in ključno...","We know what the situation is in the country, ...","Vemo , kakšna je situacija v državi , in ključ...",{},"We know what the situation is in the country ,...",{},"We know what the situation is in the country ,...","{0: 2, 2: 2, 3: 5, 4: 4, 5: 6, 6: 8, 7: 9, 8: ...","We know what the situation is in the country ,...",[],No
39,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u39\tHva...,ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u39 Than...,ParlaMint - SI _ 2014 - 08 - 01 - SDZ7 - Redna...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u39 Than...,{},ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u39 Than...,"{1: 0, 4: 2, 5: 0, 7: 0, 8: 1, 9: 0, 10: 1, 11...",ParlaMint-SI_2014-08-01-SDZ7-Redna-01.u39 Than...,[],No
40,Besedo ima Poslanska skupina Nova Slovenija – ...,The word has the Polish group New Slovenia – C...,Besedo ima Poslanska skupina Nova Slovenija – ...,{},The word has the Polish group New Slovenia – C...,{},The word has the Polish group New Slovenia – C...,"{0: 1, 1: 2, 2: 2, 3: 5, 4: 6, 5: 7, 6: 8, 7: ...",The word has the Polish group New Slovenia – C...,[],No
41,"Spoštovana gospa Ljudmila Novak, izvolite.","Dear Mrs. Lüdmila Novak, here you are.","Spoštovana gospa Ljudmila Novak , izvolite .","{2: ['Ljudmila', 'Ljudmila'], 3: ['Novak', 'No...","Dear Mrs. Lüdmila Novak , here you are .","{2: ['Lüdmila', 'Lüdmila'], 0: ['Novak', 'Nova...","Dear Mrs. Lüdmila Novak , here you are .","{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 8}","Dear Mrs. Ljudmila Novak , here you are .","[(Lüdmila, Ljudmila)]",No